# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  packages = {
    "hercules-autoscaler@workspace:." = {
      name = "hercules-autoscaler";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "hercules-autoscaler-0.0.0-9fdf1c0276";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "hercules-autoscaler";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
      bin = {
        "hercules-autoscaler" = "src/index.js";
      };
    };
  };
in
packages
