compressionLevel: 0
enableGlobalCache: true
nodeLinker: pnp
ignorePath: true
defaultSemverRangePrefix: ''
preferReuse: true
pnpZipBackend: js

supportedArchitectures:
  os:
  - 'current'
  - 'darwin'
  - 'linux'
  cpu:
  - 'current'
  - 'x64'
  - 'arm64'
  libc:
  - current
  - glibc